name: openocdcfg-generator-tests

on:
  push:
    path-ignore:
      - '**.md'
      - 'LICENSE'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8]

    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run:
          make virtualenv
      - name: Lint with pylint
        run:
          make test-lint

